
# Server
server.port=8080

# Database (H2)
spring.datasource.url=jdbc:postgresql://app_postgres:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
spring.profiles.include=secret
jwt.expiration=86400000

spring.security.user.name=admin